// Generated by Scripts/generate-dot-shape-catalog.sh — do not edit.
nonisolated struct DotShapeCatalogEntry: Equatable, Sendable {
    let category: String
    let name: String
}

nonisolated enum DotShapeCatalog {
    static let entries: [DotShapeCatalogEntry] = [
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素1"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素10"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素11"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素12"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素13"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素14"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素15"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素16"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素2"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素3"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素4"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素5"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素6"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素7"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素8"),
        DotShapeCatalogEntry(category: "像素", name: "shapes/像素/像素9"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/大葱"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/奶牛"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/工牌"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/未标题-1"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/牛角包"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/眼睛"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/胡子1"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/胡子2"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/胡子3"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/胡子4"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/花束"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/苹果"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/蛙"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/面包"),
        DotShapeCatalogEntry(category: "小物", name: "shapes/小物/风扇"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/丝带"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/彩纸1"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/彩纸2"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/彩纸3"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/彩纸4"),
        DotShapeCatalogEntry(category: "彩纸", name: "shapes/彩纸/彩纸5"),
        DotShapeCatalogEntry(category: "纽扣", name: "shapes/纽扣/星1"),
        DotShapeCatalogEntry(category: "纽扣", name: "shapes/纽扣/星2"),
        DotShapeCatalogEntry(category: "纽扣", name: "shapes/纽扣/脸"),
        DotShapeCatalogEntry(category: "纽扣", name: "shapes/纽扣/蝴蝶1"),
        DotShapeCatalogEntry(category: "纽扣", name: "shapes/纽扣/鱼1"),
    ]

    static let assetNames: [String] = entries.map(\.name)
}
