#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHAPES_DIR="$ROOT/chocho/Assets.xcassets/public/shapes"
OUT="$ROOT/chocho/DotShapeCatalog.generated.swift"
MIGRATION_OUT="$ROOT/chocho/DotShapeAssetNameMigration.generated.swift"

collect_category_assets() {
  local shapes_root="$1"
  if [[ ! -d "$shapes_root" ]]; then
    return
  fi

  for category_dir in "$shapes_root"/*/; do
    [[ -d "$category_dir" ]] || continue
    local category
    category="$(basename "$category_dir")"
    if [[ "$category" == "__staging__" ]]; then
      continue
    fi
    find "$category_dir" -maxdepth 1 \( -name '*.dataset' -o -name '*.imageset' \) -print \
      | sed -E 's|.*/||; s/\.(dataset|imageset)$//' \
      | while IFS= read -r leaf; do
          [[ -z "$leaf" ]] && continue
          printf '%s\tshapes/%s/%s\n' "$category" "$category" "$leaf"
        done
  done
}

BUILTIN_BASIC_LEAVES="心 星1 星2 星3 花1 雪"

is_builtin_basic_leaf() {
  local leaf="$1"
  for builtin in $BUILTIN_BASIC_LEAVES; do
    if [[ "$leaf" == "$builtin" ]]; then
      return 0
    fi
  done
  return 1
}

legacy_name_for() {
  local category="$1"
  local path_id="$2"
  local leaf="${path_id##*/}"

  case "$category" in
    基础)
      printf '%s' "$leaf"
      ;;
    像素)
      printf '%s.像素' "$leaf"
      ;;
    *)
      printf '%s.%s' "$leaf" "$category"
      ;;
  esac
}

previous_path_for() {
  local category="$1"
  local path_id="$2"
  local leaf="${path_id##*/}"

  case "$category" in
    像素)
      printf '像素/%s' "$leaf"
      ;;
    *)
      return 1
      ;;
  esac
}

collect_category_assets "$SHAPES_DIR" | LC_ALL=C sort -t $'\t' -k2 > "${OUT}.entries"

{
  echo "// Generated by Scripts/generate-dot-shape-catalog.sh — do not edit."
  echo "nonisolated struct DotShapeCatalogEntry: Equatable, Sendable {"
  echo "    let category: String"
  echo "    let name: String"
  echo "}"
  echo ""
  echo "nonisolated enum DotShapeCatalog {"
  echo "    static let entries: [DotShapeCatalogEntry] = ["

  while IFS=$'\t' read -r category path_id; do
    [[ -z "$category" || -z "$path_id" ]] && continue
    leaf="${path_id##*/}"
    if [[ "$category" == "基础" ]] && is_builtin_basic_leaf "$leaf"; then
      continue
    fi
    printf '        DotShapeCatalogEntry(category: "%s", name: "%s"),\n' "$category" "$path_id"
  done < "${OUT}.entries"

  echo "    ]"
  echo ""
  echo "    static let assetNames: [String] = entries.map(\\.name)"
  echo "}"
} > "$OUT"

{
  echo "// Generated by Scripts/generate-dot-shape-catalog.sh — do not edit."
  echo "nonisolated enum DotShapeAssetNameMigration {"
  echo "    static let legacyToCurrent: [String: String] = ["

  while IFS=$'\t' read -r category path_id; do
    [[ -z "$category" || -z "$path_id" ]] && continue
    leaf="${path_id##*/}"
    if [[ "$category" == "基础" ]]; then
      continue
    fi
    legacy="$(legacy_name_for "$category" "$path_id")"
    if [[ "$legacy" != "$path_id" ]]; then
      printf '        "%s": "%s",\n' "$legacy" "$path_id"
    fi
    if previous_path="$(previous_path_for "$category" "$path_id")"; then
      if [[ "$previous_path" != "$path_id" ]]; then
        printf '        "%s": "%s",\n' "$previous_path" "$path_id"
      fi
    fi
  done < "${OUT}.entries"

  echo "    ]"
  echo ""
  echo "    static func migrate(_ name: String) -> String {"
  echo "        legacyToCurrent[name] ?? name"
  echo "    }"
  echo "}"
} > "$MIGRATION_OUT"

rm -f "${OUT}.entries"

entry_count="$(grep -c 'DotShapeCatalogEntry' "$OUT" || true)"
echo "Wrote $entry_count catalog entries to $OUT"
echo "Wrote migration map to $MIGRATION_OUT"
