#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHAPES_DIR="$ROOT/chocho/Assets.xcassets/public/shapes"
PIXEL_DIR="$ROOT/chocho/Assets.xcassets/public/像素波点"
OUT="$ROOT/chocho/DotShapeCatalog.generated.swift"

collect_asset_names() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    return
  fi

  find "$dir" -maxdepth 1 \( -name '*.dataset' -o -name '*.imageset' \) -print \
    | sed -E 's|.*/||; s/\.(dataset|imageset)$//'
}

{
  collect_asset_names "$SHAPES_DIR"
  collect_asset_names "$PIXEL_DIR"
} | LC_ALL=C sort -u > "${OUT}.names"

{
  echo "// Generated by Scripts/generate-dot-shape-catalog.sh — do not edit."
  echo "nonisolated enum DotShapeCatalog {"
  echo "    static let assetNames: [String] = ["

  while IFS= read -r name; do
  [[ -z "$name" ]] && continue
  printf '        "%s",\n' "$name"
  done < "${OUT}.names"

  echo "    ]"
  echo "}"
} > "$OUT"

rm -f "${OUT}.names"

echo "Wrote $(grep -c '"' "$OUT" || true) asset names to $OUT"
